title: Install Py5 for Thonny
hero_image: images/banner.png
description: Instructions for installing Py5 plug-in within the Thonny editor
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Install Py5 for Thonny